[plugins]
shadowPlugin = { id = "com.gradleup.shadow", version.ref = "shadowGradlePlugin" }
generatePOMPlugin = { id = "ru.vyarus.java-lib", version.ref = "generatePOMGradlePlugin" }
spotBugsPlugin = { id = "com.github.spotbugs", version.ref = "spotBugsGradlePlugin" }
userdevPlugin = { id = "io.papermc.paperweight.userdev", version.ref = "userdevGradlePlugin" }

[versions]
shadowGradlePlugin = "9.2.2"
generatePOMGradlePlugin = "3.0.0"
spotBugsGradlePlugin = "6.4.4"
userdevGradlePlugin = "2.0.0-beta.19"

bukkitAPI = "1.21.10-R0.1-SNAPSHOT"
projectKorra = "1.12.0"

[libraries]
papermc-paperapi = { group = "io.papermc.paper", name = "paper-api", version.ref = "bukkitAPI" }
projectkorra-core = { group = "com.projectkorra", name = "projectkorra", version.ref = "projectKorra" }
